### ISSUE TITLE
Try picking one variable declaration format

### ISSUE THREAD

**Issue by 0xZakk** [mrwhiterk/towers_of_hanoi#3]
Using both all three is totally fine technically, but it looks a little messy. In later, more complex projects, it could also lead to some scoping issues. I recommend sticking with either `var` or `let`/`const` and not mixing them.

https://github.com/mrwhiterk/towers_of_hanoi/blob/617e9701403819abfe695672fff73b123baf9dc7/app.js#L8-L10

**Comment by mrwhiterk** [comment]
Replaced all the vars.. thanks!
