### ISSUE TITLE
Use an array here!

### ISSUE THREAD

**Issue by 0xZakk** [mrwhiterk/towers_of_hanoi#7]
If you find yourself adding numbers to your variable names, consider using a list instead. It'll make your code more dynamic!

https://github.com/mrwhiterk/towers_of_hanoi/blob/617e9701403819abfe695672fff73b123baf9dc7/app.js#L2-L4

**Comment by mrwhiterk** [comment]
Thanks for the review. I was focused on squeezing as much functionality as I could before the deadline and I know I have alot of code to clean up. Just converted these to towers array in my last commit. 👾
